name: 博客自动化部署

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "**/README.md"
      - "yarn.lock"

jobs:
  blog-cicd:
    name: 构建博客并发布到个人服务器
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2.3.4

      - name: 设置 node.js 运行环境
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"

      - name: 缓存依赖
        uses: actions/cache@v2.1.3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: 安装依赖
        run: yarn install

      - name: 构建文件
        run: yarn build--without-tsc-check

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.cs_IP }}
          username: ${{ secrets.cs_USERNAME }}
          key: ${{ secrets.cs_IDENTITY }}
          rm: "true"
          source: "dist"
          target: ${{ secrets.cs_FILEPATH }}
